# Generated by Django 2.1.3 on 2019-01-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0004_auto_20190122_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sb_color_A',
            field=models.CharField(blank=True, choices=[('Black', 'Nero'), ('White', 'Bianco')], max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='sb_color_B',
            field=models.CharField(blank=True, choices=[('Black', 'Nero'), ('White', 'Bianco')], max_length=16),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Nero'), ('White', 'Bianco')], default='White', max_length=16),
        ),
    ]
