# Generated by Django 2.1.3 on 2019-01-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioniuser',
            name='scorekeeper',
        ),
        migrations.AddField(
            model_name='ioniuser',
            name='is_scorekeeper',
            field=models.BooleanField(default=False),
        ),
    ]
