# Generated by Django 2.1.3 on 2019-01-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190122_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioniuser',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
